services: # コンテナ（サービス）の定義エリア
  # --- アプリケーションサーバー (NestJS) ---
  api:
    build:
      context: . # ビルドに必要なファイルのディレクトリ(.)
      dockerfile: Dockerfile.dev # 開発用の設計図(Dockerfile.dev)を使ってビルド
      args:
        UID: ${UID}
        GID: ${GID}
    ports:
      - "3000:3000" # ホストの3000番ポートを、コンテナの3000番に繋ぐ
    volumes:
      - .:/app # ホストのコードをコンテナ内の/appに同期させる（ホットリロード用）
      - /app/node_modules # ホスト側のnode_modulesでコンテナ内を上書きしないための「避難場所」（匿名ボリューム）
    environment: # コンテナ内で使える環境変数
      DB_HOST: db # 接続先はIPアドレスではなく、下のサービス名「db」を指定する
      DB_PORT: 5432
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      - db # dbコンテナが起動するのを待ってからapiを起動する
    # commandを書くとDockerfileのCMDが上書きされるらしい
    command: /bin/sh -c "npx prisma migrate deploy && npm run start:dev" #migrationが成功したらアプリを起動

  # --- データベースサーバー (PostgreSQL) ---
  db:
    image: postgres:15-alpine # 公式の軽量イメージをダウンロードして使う
    ports:
      - "5432:5432" # ホストからDBクライアントツール等で直接接続したい場合用
    environment: # PostgreSQLの初期設定（ユーザー名やパスワードなど）
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data # コンテナを消してもデータが消えないように、永続化領域に保存する

# データの永続化領域（ボリューム）の登録
volumes:
  postgres_data:
